# Generated by Django 2.2.17 on 2021-01-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umap', '0007_auto_20190416_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalayer',
            name='protected',
            field=models.BooleanField(default=False, help_text='protected from editor changes.', verbose_name='protected'),
        ),
    ]
