version: '3'
services:
  db:
    image: mdillon/postgis:9.6-alpine
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:latest

  app:
    image: nick-less/umap
    ports:
      - "7000:8000"
    environment:
      - DATABASE_URL=postgis://postgres@db/postgres
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=some-long-and-weirdly-unrandom-secret-key
      - ALLOWED_HOSTS=*
      - SITE_URL=http://localhost:7000/
      - LEAFLET_STORAGE_ALLOW_ANONYMOUS=True
    volumes:
      - /Users/harry/Documents/exampleworkspace/umap/uploads:/srv/umap/uploads

volumes:
  db: