version: '2'
services:
  db:
    image: mdillon/postgis:11-alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment: 
      - POSTGRES_USER=umap
      - POSTGRES_PASSWORD=umap
      - POSTGRES_DB=umap

  redis:
    image: redis:latest

  app:
    image: umap
    ports:
      - "7000:8000"
    environment:
      - DATABASE_URL=postgis://umap:umap@db/umap
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=*
      - SITE_URL=${SITE_URL}
      - LEAFLET_STORAGE_ALLOW_ANONYMOUS=False
    volumes:
      - umap_uploads:/srv/umap/uploads
volumes:
  db:
  umap_uploads:
